# 2. Introduction to NumPy
### https://jakevdp.github.io/PythonDataScienceHandbook/

## The Basics of NumPy Arrays
- **Attributes of arrays**: determining the size, shape, memory consumption, and data types of arrays
- **Indexing of arrays**: getting and setting the value of individual array elements
- **Slicing of arrays**: getting and setting smaller subarrays within a larger array
- **Reshaping of arrays**: changing the shape of a given array
- **Joining and splitting of arrays**: combining multiple arrays into one, and splitting one array into many

## NumPy Array Attributes

In [1]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

Attributes of Arrays:  
- **shape**: the size of each dimension
- **size**: the total size of the array
- **ndim**: the number of dimensions

In [2]:
print("x3 ndim is:", x3.ndim)
print("x3 shape is:", x3.shape)
print("x3 shape is:", x3.size)

x3 ndim is: 3
x3 shape is: (3, 4, 5)
x3 shape is: 60


In [3]:
print("x3 dtype is:", x3.dtype)

x3 dtype is: int64


In [4]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


In general, we expect that nbytes is equal to itemsize times size.

## Array Indexing: Accessing Single Elements


In [5]:
x1

array([5, 0, 3, 3, 7, 9])

In [6]:
x1[0]

5

In [7]:
x1[4]

7

In [8]:
x1[-1]

9

In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

In [9]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [10]:
x2[0, 0]

3

In [11]:
x2[2, 0]

1

In [12]:
x2[2, -1]

7

Values can also be modified:

In [13]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

Unlike Python lists, NumPy arrays have a fixed type. If you attempt to insert a floating-point value to an integer array, the value will be silently truncated:

In [14]:
x1[0] = 3.14159  # this will be truncated!
x1

array([3, 0, 3, 3, 7, 9])

## Array Slicing: Accessing Subarrays
**Array slicing**: [start:stop:step] with default values start=0, stop=size of dimension, step=1

### One-dimensional Subarrays

In [15]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
x[:5] # first five elements

array([0, 1, 2, 3, 4])

In [17]:
x[5:] #elements after index 5

array([5, 6, 7, 8, 9])

In [18]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

In [19]:
x[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

In [20]:
x[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [21]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

## Multi-dimensional Subarrays

In [22]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [23]:
x2[:2, :3]  # two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [24]:
x2[:3, ::2]  # all rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [25]:
x2[:, 0]  # first column of x2

array([12,  7,  1])

In [26]:
x2[0, :]  # first row of x2

array([12,  5,  2,  4])

#### Accessing Array Rows and Columns

In [27]:
print(x2[:, 0])  # first column of x2

[12  7  1]


In [28]:
print(x2[0, :])  # first row of x2

[12  5  2  4]


In [29]:
print(x2[0])  # equivalent to x2[0, :]

[12  5  2  4]


### Subarrays as No-Copy Views
Array slices return **views** rather than copies of the array data. This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies.

In [30]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [31]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [32]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [33]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


### Creating Copies of Arrays

In [34]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [35]:
x2 # the original array is changed

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [36]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [37]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## Reshaping of Arrays

In [38]:
# numpy.arange([start of interval, ]stop of interval, [step, ]dtype=None)
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [40]:
# row vector via reshape
x.reshape((1,3)) 

array([[1, 2, 3]])

In [41]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [42]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

## Array Concatenation and Splitting
### Concatenation of Arrays

In [43]:
# concatenation of arrays
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [44]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [45]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [46]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [47]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [48]:
# arrays of mixed dimensions
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [49]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

### Splitting of Arrays

In [50]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


np.split(arrwy, indices_or_sections, axis=0):
- indices_or_sections: If indices_or_sections is an integer, N, the array will be divided into N equal arrays along axis
- if indices_or_sections is a 1-D array of sorted integers, the entries indicate where along axis the array is split, for example, [2, 3] would, for axis=0 

In [51]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [52]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [53]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
